# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.Aetna.example.com:
  peer1.Aetna.example.com:
  peer0.UHG.example.com:
  peer1.UHG.example.com:

networks:
  ayush:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-Aetna
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Aetna.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.Aetna.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/Aetna.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerAetna
    networks:
      - ayush

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-UHG
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.UHG.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.UHG.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/UHG.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerUHG
    networks:
      - ayush

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - ayush

  peer0.Aetna.example.com:
    container_name: peer0.Aetna.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Aetna.example.com
    networks:
      - ayush

  peer1.Aetna.example.com:
    container_name: peer1.Aetna.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.Aetna.example.com
    networks:
      - ayush

  peer0.UHG.example.com:
    container_name: peer0.UHG.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.UHG.example.com
    networks:
      - ayush

  peer1.UHG.example.com:
    container_name: peer1.UHG.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.UHG.example.com
    networks:
      - ayush
